@startuml VueComportementale
skinparam Style strictuml
actor Utilisateur


Utilisateur -> Interface_Graphique : add_texte(buffer)


Interface_Graphique -> Buffer  : enregistreBuffer()
Interface_Graphique -> Utilisateur : changeAffichage()


@enduml
