@startuml VueComportementale
skinparam Style strictuml
actor Utilisateur


Utilisateur -> Interface_Graphique : annule_action(selection, memoire)

alt etatListAction != null
    Interface_Graphique -> Annule_Et_Refait_Action : annulerLaDerniereAction()
    Interface_Graphique -> Annule_Et_Refait_Action : enregistreEtatOriginel()
    Annule_Et_Refait_Action -> Action  : annulerAction()
    Action -> Annule_Et_Refait_Action : enregistreModification()
    Interface_Graphique -> Utilisateur : changeAffichage()
end


@enduml
